# Generated by Django 2.1.2 on 2018-10-03 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название музыки')),
                ('slug', models.SlugField(verbose_name='Слаг музыки')),
                ('text', models.TextField(blank=True, verbose_name='Текст музыки')),
                ('audio', models.FileField(upload_to='audio', verbose_name='Музыка')),
                ('data_publish', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавлений')),
                ('download', models.PositiveIntegerField(default=0, verbose_name='Число загрузок')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastanme', models.CharField(max_length=50, verbose_name='Фамилия автора')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('slug', models.SlugField(verbose_name='Слаг автора')),
                ('date_birtday', models.DateTimeField(verbose_name='Дата рождение')),
                ('photo', models.FileField(blank=True, upload_to='photo', verbose_name='Фото автора')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('slug', models.CharField(max_length=50, verbose_name='Слаг жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название изображений')),
                ('slug', models.SlugField(verbose_name='Слаг изображение')),
                ('image', models.FileField(upload_to='image', verbose_name='Изображение')),
                ('data_publish', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название видео')),
                ('slug', models.SlugField(verbose_name='Слаг видео')),
                ('text', models.TextField(blank=True, verbose_name='Текст видео')),
                ('video', models.FileField(upload_to='video', verbose_name='Видео')),
                ('data_publish', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление')),
                ('download', models.PositiveIntegerField(default=0, verbose_name='Число загрузок')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Author'),
        ),
        migrations.AddField(
            model_name='audio',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Genre'),
        ),
    ]
