# Generated by Django 2.1.2 on 2018-10-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='lastanme',
            new_name='lastname',
        ),
    ]
