# Generated by Django 2.1.2 on 2018-10-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20181003_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыки'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видое'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.RemoveField(
            model_name='image',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
    ]
