# Generated by Django 2.1.2 on 2018-10-03 11:03

from django.db import migrations, models
import new.models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20181003_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to=new.models.generate_filename, verbose_name='Музыка'),
        ),
    ]
