# Generated by Django 2.1.2 on 2018-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_auto_20181003_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='', verbose_name='Музыка'),
        ),
    ]
