# Generated by Django 2.1.2 on 2018-10-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_auto_20181003_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='audio', verbose_name='Музыка'),
        ),
    ]
